### ISSUE TITLE
FR: Add an app connector option

### ISSUE THREAD

**Issue by arunoruto** [dkaser/unraid-tailscale#103]
Tailscale introduced the [app connector](https://tailscale.com/kb/1281/app-connectors) feature today, and it would be nice to have an option to provide a tag name in the settings menu. I guess manually doing it over the shell should work for now, but it would be a nicer user experience.

**Comment by dkaser** [comment]
This isn't something that I plan to add to the plugin itself. Managing tags would be difficult for the plugin (since they can be changed externally, have permissions requirements based on tailnet policy, etc.). For users wanting a graphical option, tags can be assigned via the Tailscale admin console after the server is connected. 

Also: Tailscale is going to be improving the web settings interface (the first page in plugin settings) to allow for more settings to be controlled. That would be a more appropriate place for control of tags to eventually land (and is more in line with what I would like for the plugin -- Tailscale controls the Tailscale settings, the plugin controls settings to make Unraid work well with it).
