### ISSUE TITLE
vm with tailscale inside unraid with tailscale -- broken dns

### ISSUE THREAD

**Issue by asg0451** [dkaser/unraid-tailscale#85]
I have an unraid box with this tailscale plugin, works great. I made a new ubuntu vm in unraid, and installed tailscale on it, and now the vm is unable to resolve any dns addresses. Is this use case supposed to work? are there any workarounds? Thanks!

**Comment by dkaser** [comment]
Assuming that you're using the public bridge for your VM network, the Tailscale inside the VM shouldn't be affected by anything that this plugin is doing on the host. 

If you're using the private bridge, I could see things getting a little trickier, particularly if you have MagicDNS enabled in the plugin settings. I could see that causing weird DNS problems since it overwrites resolv.conf on the host, and Tailscale on the host might not respond to queries from the VM. 

If MagicDNS is turned on for the plugin, The simplest solution would probably be to turn it off... most use cases don't benefit from that being enabled.
