### ISSUE TITLE
"Not Connected" status in Admin Console prevents exit node connection from some devices

### ISSUE THREAD

**Issue by tayden-flitcroft** [dkaser/unraid-tailscale#91]
Looking through the support thread, I believe this is a known issue, but to reiterate, the connectivity status in the Admin Console is incorrect for the plugin. In the support thread, there was some speculation that this may not affect ; however, however after trying to get Tailscale on my iOS Devices and my Macbook Pro, I believe this is an actual issue. On my Windows desktop I can connect to the exit node on my Unraid box no problem, but on the Apple devices I have tried, the option is completely greyed out. This is likely because it is doing a check to what is getting reported to the console, which shows it is not connected. My Unraid version is 6.12.1 and looking at the picture of the person also experiencing the issue, both his units are > v. 6.12 as well.

Thank you in advance.

[Here's the post](https://forums.unraid.net/topic/136889-plugin-tailscale/?do=findComment&comment=1273960)

**Comment by dkaser** [comment]
Ultimately, this isn't something that can be fixed with the plugin scripts... it's actually a problem with the tailscale binary/control plane itself. I won't be able to fix that until tailscale itself is updated to correct the problem. 

The best thing for you to do would be create an issue over at tailscale/tailscale so that the developers over there can take a look at what's happening.
